version: '3'

services:
  web:
    image: up-web:latest
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
    depends_on:
      - db

  db:
    image: mysql:5.7.42
    platform: linux/amd64
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - 8080:80
    depends_on:
      - db

volumes:
  db_data: